// ============================================================
// VESMÍRNÁ EXPEDICE SLOV – databáze otázek
// 3. ročník ZŠ
//
// Jak přidat otázku: zkopíruj existující blok { ... }, uprav
// texty a ulož soubor. Nic jiného měnit nemusíš.
//
// Typy otázek:
//   "dopln" – doplňování písmene do věty (mezera se píše jako _)
//   "abc"   – výběr z možností
//   "chyt"  – chyť (klepni na) správnou odpověď mezi bublinami
//
// "spravna" je pořadí správné možnosti v poli "moznosti",
// počítá se od nuly (0 = první možnost).
// ============================================================

const OTAZKY = {

  // ----------------------------------------------------------
  // PLANETA YPSILONKA – vyjmenovaná slova
  // ----------------------------------------------------------

  "vs_b": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Na louce se pásla kob_la.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Vzpomeň si na řadu: být, bydlit, obyvatel, byt… kobyla, býk.",
      vysvetleni: "KOBYLA je vyjmenované slovo po B, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Na dvoře bučel velký b_k.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Je to zvíře z řady vyjmenovaných slov po B.",
      vysvetleni: "BÝK je vyjmenované slovo po B, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "V našem domě je pět b_tů.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Byt, příbytek, nábytek – všechna patří do řady po B.",
      vysvetleni: "BYT je vyjmenované slovo po B, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Babička natrhala léčivou b_linu.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Rostlina z řady vyjmenovaných slov po B.",
      vysvetleni: "BYLINA je vyjmenované slovo po B, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Kůň se lekl b_če.",
      moznosti: ["i", "y"], spravna: 0,
      napoveda: "Je BIČ mezi vyjmenovanými slovy po B? Není!",
      vysvetleni: "BIČ není vyjmenované slovo ani slovo příbuzné, proto píšeme měkké i." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["Obivatelé města se sešli na náměstí.", "Obyvatelé města se sešli na náměstí.", "Obývatelé města se sešli na náměstí."], spravna: 1,
      napoveda: "Slovo OBYVATEL patří do řady vyjmenovaných slov po B a má krátké y.",
      vysvetleni: "OBYVATELÉ – vyjmenované slovo po B, píšeme krátké tvrdé y." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i:",
      moznosti: ["bič", "býk", "bydlet", "obyčej"], spravna: 0,
      napoveda: "Tři z těch slov jsou vyjmenovaná po B. Jedno mezi ně nepatří.",
      vysvetleni: "BIČ není vyjmenované slovo po B, proto v něm píšeme měkké i. Ostatní slova jsou vyjmenovaná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po B:",
      moznosti: ["dobytek", "bota", "buben", "bageta"], spravna: 0,
      napoveda: "Být, bydlit, obyvatel, byt, příbytek, nábytek, dobytek…",
      vysvetleni: "DOBYTEK patří do řady vyjmenovaných slov po B." }
  ],

  "vs_l": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "U řeky stál starý ml_n.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Slyšet, mlýn, blýskat se, polykat…",
      vysvetleni: "MLÝN je vyjmenované slovo po L, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Po běhání mě bolí l_tko.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Část nohy z řady vyjmenovaných slov po L.",
      vysvetleni: "LÝTKO je vyjmenované slovo po L, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "V zimě jezdíme na l_žích.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Lyže patří do řady vyjmenovaných slov po L.",
      vysvetleni: "LYŽE je vyjmenované slovo po L, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Večer se venku bl_skalo.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Blýskat se – hledej v řadě po L.",
      vysvetleni: "BLÝSKAT SE je vyjmenované slovo po L, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Nesmíme pl_tvat vodou.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Plynout, plýtvat – obě jsou v řadě po L.",
      vysvetleni: "PLÝTVAT je vyjmenované slovo po L, proto píšeme tvrdé ý." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["V dálce vzlikalo dítě.", "V dálce vzlykalo dítě.", "V dálce vzlíkalo dítě."], spravna: 1,
      napoveda: "VZLYKAT patří do řady vyjmenovaných slov po L.",
      vysvetleni: "VZLYKALO – vyjmenované slovo po L, píšeme tvrdé y." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i (í):",
      moznosti: ["lípa", "mlýn", "lyže", "plyš"], spravna: 0,
      napoveda: "Strom, který není v řadě vyjmenovaných slov po L.",
      vysvetleni: "LÍPA není vyjmenované slovo po L, proto píšeme měkké í. Ostatní slova jsou vyjmenovaná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po L:",
      moznosti: ["pelyněk", "letadlo", "lampa", "lednička"], spravna: 0,
      napoveda: "Je to hořká bylina, poslední slovo v řadě po L.",
      vysvetleni: "PELYNĚK patří do řady vyjmenovaných slov po L." }
  ],

  "vs_m": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "M_dlo v koupelně krásně voní.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Mýdlem se MYJEME. Je příbuzné se slovem MÝT.",
      vysvetleni: "MÝDLO je příbuzné s vyjmenovaným slovem MÝT, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Na zahradě bzučel hm_z.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "My, mýt, myslit, mýlit se, hmyz…",
      vysvetleni: "HMYZ je vyjmenované slovo po M, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Kočka chytila m_š.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Malé zvířátko z řady vyjmenovaných slov po M.",
      vysvetleni: "MYŠ je vyjmenované slovo po M, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Nesmíš se v počítání m_lit.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Mýlit se je v řadě vyjmenovaných slov po M.",
      vysvetleni: "MÝLIT SE je vyjmenované slovo po M, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Kuchař m_chal polévku vařečkou.",
      moznosti: ["í", "ý"], spravna: 0,
      napoveda: "Je MÍCHAT mezi vyjmenovanými slovy po M? Není!",
      vysvetleni: "MÍCHAT není vyjmenované slovo ani slovo příbuzné, proto píšeme měkké í." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["Hlemížď nese svůj domeček.", "Hlemyžď nese svůj domeček.", "Hlemýžď nese svůj domeček."], spravna: 2,
      napoveda: "Hlemýžď je v řadě po M a má dlouhé ý.",
      vysvetleni: "HLEMÝŽĎ – vyjmenované slovo po M, píšeme dlouhé tvrdé ý." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i (í):",
      moznosti: ["mísa", "myslet", "mýt", "zamykat"], spravna: 0,
      napoveda: "Nádoba v kuchyni. V řadě po M ji nenajdeš.",
      vysvetleni: "MÍSA není vyjmenované slovo po M, proto píšeme měkké í. Ostatní slova jsou vyjmenovaná nebo příbuzná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po M:",
      moznosti: ["Litomyšl", "mikina", "minuta", "míč"], spravna: 0,
      napoveda: "Je to město. Najdeš ho na konci řady po M.",
      vysvetleni: "LITOMYŠL je město z řady vyjmenovaných slov po M." }
  ],

  "vs_p": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Netop_r spí přes den v jeskyni.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Létající zvíře z řady vyjmenovaných slov po P.",
      vysvetleni: "NETOPÝR je vyjmenované slovo po P, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Kůň má tvrdá kop_ta.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Pýcha, pytel, pysk, netopýr, slepýš, pyl, kopyto…",
      vysvetleni: "KOPYTO je vyjmenované slovo po P, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Na jaře létá vzduchem p_l z květin.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Pyl přenášejí včely. Je v řadě po P.",
      vysvetleni: "PYL je vyjmenované slovo po P, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Hvězdy se třp_tí na obloze.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Třpytit se je v řadě vyjmenovaných slov po P.",
      vysvetleni: "TŘPYTIT SE je vyjmenované slovo po P, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "P_šná princezna se na nikoho neusmála.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Pyšný je příbuzné slovo se slovem PÝCHA.",
      vysvetleni: "PYŠNÁ je příbuzné slovo k vyjmenovanému slovu PÝCHA, proto píšeme tvrdé y." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["Slepýš se vyhříval na kameni.", "Slepíš se vyhříval na kameni.", "Slepýš se vihříval na kameni."], spravna: 0,
      napoveda: "SLEPÝŠ je zvíře z řady po P. A VYHŘÍVAL se píše s předponou vy-.",
      vysvetleni: "SLEPÝŠ je vyjmenované slovo po P a VYHŘÍVAL má předponu vy-, obě píšeme s tvrdým y (ý)." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i (í):",
      moznosti: ["písek", "pytel", "pýr", "kopyto"], spravna: 0,
      napoveda: "Najdeš ho na pískovišti, ale v řadě po P ne.",
      vysvetleni: "PÍSEK není vyjmenované slovo po P, proto píšeme měkké í. Ostatní slova jsou vyjmenovaná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po P:",
      moznosti: ["klopýtat", "pírko", "píseň", "pila"], spravna: 0,
      napoveda: "Znamená to zakopávat při chůzi.",
      vysvetleni: "KLOPÝTAT patří do řady vyjmenovaných slov po P." }
  ],

  "vs_s": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "K svačině máme chléb se s_rem.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Syn, sytý, sýr, syrový…",
      vysvetleni: "SÝR je vyjmenované slovo po S, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Na krmítko přiletěla s_kora.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Ptáček z řady vyjmenovaných slov po S.",
      vysvetleni: "SÝKORA je vyjmenované slovo po S, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Venku bylo s_chravé počasí.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Sychravý znamená chladný a vlhký. Je v řadě po S.",
      vysvetleni: "SYCHRAVÝ je vyjmenované slovo po S, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Maminka nas_pala mouku do mísy.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Sypat je v řadě vyjmenovaných slov po S.",
      vysvetleni: "NASYPALA je příbuzné slovo k vyjmenovanému slovu SYPAT, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "S_lný vítr lámal větve.",
      moznosti: ["i", "y"], spravna: 0,
      napoveda: "Je SILNÝ mezi vyjmenovanými slovy po S? Není!",
      vysvetleni: "SILNÝ není vyjmenované slovo ani slovo příbuzné, proto píšeme měkké i." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["Sin pomáhal tatínkovi.", "Syn pomáhal tatínkovi.", "Sýn pomáhal tatínkovi."], spravna: 1,
      napoveda: "SYN je první slovo v řadě po S a má krátké y.",
      vysvetleni: "SYN – vyjmenované slovo po S, píšeme krátké tvrdé y." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i (í):",
      moznosti: ["síla", "sysel", "syčet", "sytý"], spravna: 0,
      napoveda: "Tři z těch slov jsou vyjmenovaná po S. Jedno mezi ně nepatří.",
      vysvetleni: "SÍLA není vyjmenované slovo po S, proto píšeme měkké í. Ostatní slova jsou vyjmenovaná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po S:",
      moznosti: ["sýček", "sešit", "sedlo", "síť"], spravna: 0,
      napoveda: "Malá sova z řady vyjmenovaných slov po S.",
      vysvetleni: "SÝČEK patří do řady vyjmenovaných slov po S." }
  ],

  "vs_v": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "V_dra plavala v řece.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Vy, vysoký, výt, výskat, zvykat, žvýkat, vydra…",
      vysvetleni: "VYDRA je vyjmenované slovo po V, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "V noci v lese houkal v_r.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Houká, protože je to sova. Pták VÝR se píše s tvrdým ý.",
      vysvetleni: "VÝR je pták (velká sova) a je to vyjmenované slovo po V. Pozor: VÍR s měkkým í je točící se voda." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Pomalu si zv_kám na novou školu.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Zvykat je v řadě vyjmenovaných slov po V.",
      vysvetleni: "ZVYKÁM je tvar vyjmenovaného slova ZVYKAT, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Ve škole nesmíme žv_kat žvýkačku.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Žvýkat je v řadě vyjmenovaných slov po V.",
      vysvetleni: "ŽVÝKAT je vyjmenované slovo po V, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "V_dím na obloze krásnou duhu.",
      moznosti: ["i", "y"], spravna: 0,
      napoveda: "Je VIDĚT mezi vyjmenovanými slovy po V? Není!",
      vysvetleni: "VIDĚT není vyjmenované slovo ani slovo příbuzné, proto píšeme měkké i." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["Visoký strom rostl u cesty.", "Vysoký strom rostl u cesty.", "Vysoký strom rostl u cesti."], spravna: 1,
      napoveda: "VYSOKÝ je vyjmenované slovo po V. A po T píšeme tvrdé y.",
      vysvetleni: "VYSOKÝ je vyjmenované slovo po V. Ve slově CESTY píšeme y, protože T je tvrdá souhláska." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i:",
      moznosti: ["vidlička", "vydra", "povyk", "výskat"], spravna: 0,
      napoveda: "Jíme s ní. V řadě po V ji nenajdeš.",
      vysvetleni: "VIDLIČKA není vyjmenované slovo po V, proto píšeme měkké i. Ostatní slova jsou vyjmenovaná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po V:",
      moznosti: ["povyk", "víla", "vítr", "vidle"], spravna: 0,
      napoveda: "Znamená to hluk a křik.",
      vysvetleni: "POVYK patří do řady vyjmenovaných slov po V." }
  ],

  "vs_z": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Přijď dnes domů brz_.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Brzy, jazyk, nazývat se, Ruzyně.",
      vysvetleni: "BRZY je vyjmenované slovo po Z, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Ukázal jsem paní doktorce jaz_k.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Máš ho v puse. Je v řadě po Z.",
      vysvetleni: "JAZYK je vyjmenované slovo po Z, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Tato květina se naz_vá tulipán.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "Nazývat se je v řadě vyjmenovaných slov po Z.",
      vysvetleni: "NAZÝVÁ SE je tvar vyjmenovaného slova NAZÝVAT SE, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Letadlo přistálo v Ruz_ni.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "Ruzyně je část Prahy s letištěm. Je v řadě po Z.",
      vysvetleni: "RUZYNĚ je vyjmenované slovo po Z, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Z_ma letos přišla brzy.",
      moznosti: ["i", "y"], spravna: 0,
      napoveda: "Je ZIMA mezi vyjmenovanými slovy po Z? Není!",
      vysvetleni: "ZIMA není vyjmenované slovo ani slovo příbuzné, proto píšeme měkké i." },
    { typ: "abc", zadani: "Vyber větu, která je napsaná správně:",
      moznosti: ["Brzi ráno zpívají ptáci.", "Brzy ráno zpívají ptáci.", "Brzý ráno zpívají ptáci."], spravna: 1,
      napoveda: "BRZY je vyjmenované slovo po Z a má krátké y.",
      vysvetleni: "BRZY – vyjmenované slovo po Z, píšeme krátké tvrdé y." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém píšeme měkké i:",
      moznosti: ["zima", "jazyk", "brzy", "nazývat"], spravna: 0,
      napoveda: "Roční období, které v řadě po Z nenajdeš.",
      vysvetleni: "ZIMA není vyjmenované slovo po Z, proto píšeme měkké i. Ostatní slova jsou vyjmenovaná." },
    { typ: "chyt", zadani: "Chyť vyjmenované slovo po Z:",
      moznosti: ["jazyk", "zebra", "zvon", "zrcadlo"], spravna: 0,
      napoveda: "Brzy, jazyk, nazývat se, Ruzyně.",
      vysvetleni: "JAZYK patří do řady vyjmenovaných slov po Z." }
  ],

  "vs_mix": [
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Netopýři vylétají brz_ večer.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "BRZY je vyjmenované slovo po Z.",
      vysvetleni: "BRZY je vyjmenované slovo po Z, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Myška ukusovala kousek s_ra.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "SÝR najdeš v řadě vyjmenovaných slov po S.",
      vysvetleni: "SÝRA je tvar vyjmenovaného slova SÝR (po S), proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Na pastvině se pásla kobyla i b_k.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "BÝK je v řadě vyjmenovaných slov po B.",
      vysvetleni: "BÝK je vyjmenované slovo po B, proto píšeme tvrdé ý." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "O prázdninách jsme l_žovali na horách.",
      moznosti: ["y", "i"], spravna: 0,
      napoveda: "LYŽOVAT je příbuzné se slovem LYŽE (po L).",
      vysvetleni: "LYŽOVALI je příbuzné slovo k vyjmenovanému slovu LYŽE, proto píšeme tvrdé y." },
    { typ: "dopln", zadani: "Doplň správné písmeno:", veta: "Umyl jsem si ruce m_dlem.",
      moznosti: ["ý", "í"], spravna: 0,
      napoveda: "MÝDLO je příbuzné se slovem MÝT (po M).",
      vysvetleni: "MÝDLEM je tvar slova MÝDLO, které je příbuzné s vyjmenovaným slovem MÝT, proto píšeme tvrdé ý." },
    { typ: "abc", zadani: "Které slovo je napsané správně?",
      moznosti: ["hmiz", "hmyz", "hmýz"], spravna: 1,
      napoveda: "Je v řadě vyjmenovaných slov po M a má krátké y.",
      vysvetleni: "HMYZ – vyjmenované slovo po M, píšeme krátké tvrdé y." },
    { typ: "abc", zadani: "Vyber větu bez chyby:",
      moznosti: ["Vidra plave v řece.", "Vydra plave v řece.", "Vídra plave v řece."], spravna: 1,
      napoveda: "VYDRA je v řadě vyjmenovaných slov po V.",
      vysvetleni: "VYDRA – vyjmenované slovo po V, píšeme krátké tvrdé y." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém je CHYBA:",
      moznosti: ["mlín", "myš", "jazyk", "pytel"], spravna: 0,
      napoveda: "Jedno slovo má měkké í tam, kde patří tvrdé ý.",
      vysvetleni: "Správně je MLÝN – vyjmenované slovo po L, píšeme tvrdé ý." },
    { typ: "chyt", zadani: "Chyť slovo, ve kterém je CHYBA:",
      moznosti: ["sichravý", "lyže", "býk", "vysoký"], spravna: 0,
      napoveda: "Jedno slovo má měkké i tam, kde patří tvrdé y.",
      vysvetleni: "Správně je SYCHRAVÝ – vyjmenované slovo po S, píšeme tvrdé y." },
    { typ: "abc", zadani: "Ve kterém slově píšeme měkké i?",
      moznosti: ["l_ška", "ml_n", "pl_n"], spravna: 0,
      napoveda: "Dvě z těch slov najdeš v řadě po L. Jedno tam není.",
      vysvetleni: "LIŠKA není vyjmenované slovo, píšeme měkké i. MLÝN a PLYN jsou vyjmenovaná slova po L." }
  ],

  // ----------------------------------------------------------
  // PLANETA PODSTATKA – podstatná jména
  // ----------------------------------------------------------

  "pj_rod": [
    { typ: "abc", zadani: "Urči rod podstatného jména: PES",
      moznosti: ["rod mužský", "rod ženský", "rod střední"], spravna: 0,
      napoveda: "Pomůže ti ukazovací slovo: TEN, TA, nebo TO pes?",
      vysvetleni: "Říkáme TEN pes, proto je to rod mužský." },
    { typ: "abc", zadani: "Urči rod podstatného jména: KOČKA",
      moznosti: ["rod mužský", "rod ženský", "rod střední"], spravna: 1,
      napoveda: "TEN, TA, nebo TO kočka?",
      vysvetleni: "Říkáme TA kočka, proto je to rod ženský." },
    { typ: "abc", zadani: "Urči rod podstatného jména: MĚSTO",
      moznosti: ["rod mužský", "rod ženský", "rod střední"], spravna: 2,
      napoveda: "TEN, TA, nebo TO město?",
      vysvetleni: "Říkáme TO město, proto je to rod střední." },
    { typ: "abc", zadani: "Které ukazovací slovo patří ke slovu ŽIDLE?",
      moznosti: ["ten", "ta", "to"], spravna: 1,
      napoveda: "Zkus si to říct nahlas: ten židle, ta židle, to židle.",
      vysvetleni: "Říkáme TA židle. ŽIDLE je rodu ženského." },
    { typ: "abc", zadani: "Které ukazovací slovo patří ke slovu AUTO?",
      moznosti: ["ten", "ta", "to"], spravna: 2,
      napoveda: "Zkus si to říct nahlas: ten auto, ta auto, to auto.",
      vysvetleni: "Říkáme TO auto. AUTO je rodu středního." },
    { typ: "chyt", zadani: "Chyť podstatné jméno rodu mužského:",
      moznosti: ["stůl", "okno", "kniha", "pole"], spravna: 0,
      napoveda: "Hledej slovo, ke kterému patří TEN.",
      vysvetleni: "Říkáme TEN stůl, proto je STŮL rodu mužského. Okno a pole jsou TO (střední), kniha je TA (ženský)." },
    { typ: "chyt", zadani: "Chyť podstatné jméno rodu středního:",
      moznosti: ["kuře", "pes", "máma", "les"], spravna: 0,
      napoveda: "Hledej slovo, ke kterému patří TO.",
      vysvetleni: "Říkáme TO kuře, proto je KUŘE rodu středního. Pes a les jsou TEN (mužský), máma je TA (ženský)." },
    { typ: "abc", zadani: "Urči rod podstatného jména: UČITELKA",
      moznosti: ["rod mužský", "rod ženský", "rod střední"], spravna: 1,
      napoveda: "TEN, TA, nebo TO učitelka?",
      vysvetleni: "Říkáme TA učitelka, proto je to rod ženský." }
  ],

  "pj_cislo": [
    { typ: "abc", zadani: "Urči číslo podstatného jména: DĚTI",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Je to jedno dítě, nebo víc dětí?",
      vysvetleni: "DĚTI označují více osob, proto je to číslo množné. Jedno dítě = číslo jednotné." },
    { typ: "abc", zadani: "Urči číslo podstatného jména: PES",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 0,
      napoveda: "Je to jeden pes, nebo víc psů?",
      vysvetleni: "PES označuje jedno zvíře, proto je to číslo jednotné." },
    { typ: "abc", zadani: "Urči číslo podstatného jména: STROMY",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Je to jeden strom, nebo víc stromů?",
      vysvetleni: "STROMY označují více stromů, proto je to číslo množné." },
    { typ: "abc", zadani: "Urči číslo podstatného jména: MĚSTO",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 0,
      napoveda: "Je to jedno město, nebo víc měst?",
      vysvetleni: "MĚSTO označuje jedno město, proto je to číslo jednotné." },
    { typ: "chyt", zadani: "Chyť slovo v čísle množném:",
      moznosti: ["koťata", "kočka", "dům", "židle"], spravna: 0,
      napoveda: "Hledej slovo, které označuje víc věcí nebo zvířat najednou.",
      vysvetleni: "KOŤATA = více koťat, proto číslo množné. Kočka, dům i (jedna) židle označují jednu věc." },
    { typ: "chyt", zadani: "Chyť slovo v čísle jednotném:",
      moznosti: ["kniha", "knihy", "okna", "psi"], spravna: 0,
      napoveda: "Hledej slovo, které označuje jen jednu věc.",
      vysvetleni: "KNIHA = jedna kniha, proto číslo jednotné. Knihy, okna a psi označují víc věcí." },
    { typ: "abc", zadani: "Kolik věcí označuje slovo TUŽKY?",
      moznosti: ["jednu tužku", "více tužek"], spravna: 1,
      napoveda: "Jedna tužka, dvě TUŽKY, tři TUŽKY…",
      vysvetleni: "TUŽKY označují více tužek, proto je to číslo množné." },
    { typ: "abc", zadani: "Urči číslo podstatného jména: OČI",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Jedno oko, dvě OČI.",
      vysvetleni: "OČI označují více očí (máme dvě), proto je to číslo množné. Jedno OKO = číslo jednotné." }
  ],

  "pj_pad": [
    { typ: "abc", zadani: "Jakou otázkou se ptáme na 1. pád?",
      moznosti: ["KDO, CO?", "KOHO, ČEHO?", "KOMU, ČEMU?"], spravna: 0,
      napoveda: "První pád je ten, kterým slovo jmenujeme: KDO to je? CO to je?",
      vysvetleni: "Na 1. pád se ptáme otázkou KDO, CO? Například: KDO štěká? Pes." },
    { typ: "abc", zadani: "Otázkou KOHO, ČEHO? (bez koho, bez čeho) se ptáme na:",
      moznosti: ["1. pád", "2. pád", "4. pád"], spravna: 1,
      napoveda: "Pomáhá slovíčko BEZ: bez KOHO, bez ČEHO?",
      vysvetleni: "Otázka KOHO, ČEHO? patří ke 2. pádu. Například: bez ČEHO? Bez vody." },
    { typ: "abc", zadani: "Ve větě „Pes štěká.“ je slovo PES v pádě:",
      moznosti: ["1. pád", "3. pád", "4. pád"], spravna: 0,
      napoveda: "Zeptej se: KDO, CO štěká?",
      vysvetleni: "Ptáme se: KDO, CO štěká? Pes. Otázka KDO, CO? patří k 1. pádu." },
    { typ: "abc", zadani: "Ve větě „Vidím psa.“ je slovo PSA v pádě:",
      moznosti: ["1. pád", "2. pád", "4. pád"], spravna: 2,
      napoveda: "Zeptej se: vidím KOHO, CO?",
      vysvetleni: "Ptáme se: vidím KOHO, CO? Psa. Otázka KOHO, CO? patří ke 4. pádu." },
    { typ: "abc", zadani: "Ve větě „Jdu ke škole.“ je slovo KE ŠKOLE v pádě:",
      moznosti: ["2. pád", "3. pád", "6. pád"], spravna: 1,
      napoveda: "Zeptej se: jdu ke KOMU, ČEMU?",
      vysvetleni: "Ptáme se: jdu ke KOMU, ČEMU? Ke škole. Otázka KOMU, ČEMU? patří ke 3. pádu." },
    { typ: "abc", zadani: "Voláme: „Petře, pojď sem!“ Slovo PETŘE je v pádě:",
      moznosti: ["1. pád", "5. pád", "7. pád"], spravna: 1,
      napoveda: "Kterým pádem voláme a oslovujeme?",
      vysvetleni: "5. pádem oslovujeme a voláme: Petře! Maminko! Pane učiteli!" },
    { typ: "abc", zadani: "Ve větě „Mluvíme o mamince.“ je slovo O MAMINCE v pádě:",
      moznosti: ["3. pád", "6. pád", "7. pád"], spravna: 1,
      napoveda: "Zeptej se: mluvíme O KOM, O ČEM?",
      vysvetleni: "Ptáme se: mluvíme O KOM, O ČEM? O mamince. Otázka O KOM, O ČEM? patří k 6. pádu." },
    { typ: "abc", zadani: "Ve větě „Píšu tužkou.“ je slovo TUŽKOU v pádě:",
      moznosti: ["4. pád", "6. pád", "7. pád"], spravna: 2,
      napoveda: "Zeptej se: píšu KÝM, ČÍM?",
      vysvetleni: "Ptáme se: píšu KÝM, ČÍM? Tužkou. Otázka KÝM, ČÍM? patří k 7. pádu." }
  ],

  "pj_mix": [
    { typ: "abc", zadani: "Urči rod podstatného jména: SLUNCE",
      moznosti: ["rod mužský", "rod ženský", "rod střední"], spravna: 2,
      napoveda: "TEN, TA, nebo TO slunce?",
      vysvetleni: "Říkáme TO slunce, proto je to rod střední." },
    { typ: "abc", zadani: "Urči číslo podstatného jména: HRAČKY",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Jedna hračka, nebo víc hraček?",
      vysvetleni: "HRAČKY označují více hraček, proto je to číslo množné." },
    { typ: "abc", zadani: "Ve větě „Čtu knihu.“ je slovo KNIHU v pádě:",
      moznosti: ["1. pád", "4. pád", "7. pád"], spravna: 1,
      napoveda: "Zeptej se: čtu KOHO, CO?",
      vysvetleni: "Ptáme se: čtu KOHO, CO? Knihu. Otázka KOHO, CO? patří ke 4. pádu." },
    { typ: "chyt", zadani: "Chyť slovo rodu ženského v čísle množném:",
      moznosti: ["knihy", "pes", "města", "stůl"], spravna: 0,
      napoveda: "Hledej slovo: TA + víc věcí najednou.",
      vysvetleni: "KNIHY – jedna KNIHA je TA (rod ženský) a knihy jsou víc než jedna (číslo množné)." },
    { typ: "abc", zadani: "Urči rod a číslo: KOŤATA",
      moznosti: ["rod střední, číslo množné", "rod ženský, číslo jednotné", "rod mužský, číslo množné"], spravna: 0,
      napoveda: "Jedno KOTĚ je TO kotě. A koťat je víc.",
      vysvetleni: "Jedno kotě = TO kotě, rod střední. KOŤATA jsou víc než jedno, proto číslo množné." },
    { typ: "abc", zadani: "Ve větě „Rostlina nemůže žít bez vody.“ je slovo VODY v pádě:",
      moznosti: ["1. pád", "2. pád", "6. pád"], spravna: 1,
      napoveda: "Zeptej se: bez KOHO, ČEHO?",
      vysvetleni: "Ptáme se: bez KOHO, ČEHO? Bez vody. Otázka KOHO, ČEHO? patří ke 2. pádu." },
    { typ: "chyt", zadani: "Chyť podstatné jméno:",
      moznosti: ["škola", "běhat", "veselý", "rychle"], spravna: 0,
      napoveda: "Podstatná jména jsou názvy osob, zvířat a věcí. Ukážeme na ně TEN, TA, TO.",
      vysvetleni: "ŠKOLA je podstatné jméno (TA škola). Běhat je sloveso, veselý je přídavné jméno, rychle je příslovce." },
    { typ: "abc", zadani: "Urči rod a číslo: PSI",
      moznosti: ["rod mužský, číslo množné", "rod mužský, číslo jednotné", "rod střední, číslo množné"], spravna: 0,
      napoveda: "Jeden PES je TEN pes. A psů je víc.",
      vysvetleni: "Jeden pes = TEN pes, rod mužský. PSI jsou víc než jeden, proto číslo množné." }
  ],

  // ----------------------------------------------------------
  // STANICE SLOVESNÁ – slovesa
  // ----------------------------------------------------------

  "sl_osoba": [
    { typ: "abc", zadani: "Urči osobu: (já) ČTU",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 0,
      napoveda: "1. osoba = já, my. 2. osoba = ty, vy. 3. osoba = on, ona, ono, oni.",
      vysvetleni: "ČTU si říkám JÁ o sobě. JÁ je 1. osoba." },
    { typ: "abc", zadani: "Urči osobu: (ty) PÍŠEŠ",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 1,
      napoveda: "Komu to říkáme? TY píšeš.",
      vysvetleni: "PÍŠEŠ říkáme TOBĚ. TY je 2. osoba." },
    { typ: "abc", zadani: "Urči osobu: (on) SPÍ",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 2,
      napoveda: "O kom mluvíme? ON spí.",
      vysvetleni: "SPÍ říkáme o NĚM. ON, ONA, ONO je 3. osoba." },
    { typ: "abc", zadani: "Urči osobu: ZPÍVÁME",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 0,
      napoveda: "Kdo zpívá? MY zpíváme.",
      vysvetleni: "ZPÍVÁME říkáme o sobě: MY. Proto je to 1. osoba." },
    { typ: "abc", zadani: "Urči osobu: MALUJETE",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 1,
      napoveda: "Kdo maluje? VY malujete.",
      vysvetleni: "MALUJETE říkáme VÁM. VY je 2. osoba." },
    { typ: "abc", zadani: "Urči osobu: BĚHAJÍ",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 2,
      napoveda: "Kdo běhá? ONI běhají.",
      vysvetleni: "BĚHAJÍ říkáme o NICH. ONI je 3. osoba." },
    { typ: "chyt", zadani: "Chyť sloveso v 1. osobě:",
      moznosti: ["píšu", "píšeš", "píše", "píšete"], spravna: 0,
      napoveda: "Hledej tvar, ke kterému se hodí JÁ.",
      vysvetleni: "JÁ PÍŠU – 1. osoba. Píšeš (ty) a píšete (vy) jsou 2. osoba, píše (on) je 3. osoba." },
    { typ: "abc", zadani: "Které slovo si řekneš před slovesem VAŘÍŠ?",
      moznosti: ["já", "ty", "on"], spravna: 1,
      napoveda: "Já vařím, ty vaříš, on vaří.",
      vysvetleni: "TY VAŘÍŠ – sloveso VAŘÍŠ je ve 2. osobě." }
  ],

  "sl_cislo": [
    { typ: "abc", zadani: "Urči číslo slovesa: ČTEME",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Čte jeden člověk, nebo víc lidí? MY čteme.",
      vysvetleni: "ČTEME říká více lidí (MY), proto je to číslo množné." },
    { typ: "abc", zadani: "Urči číslo slovesa: ČTU",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 0,
      napoveda: "Čte jeden člověk, nebo víc lidí? JÁ čtu.",
      vysvetleni: "ČTU říká jeden člověk (JÁ), proto je to číslo jednotné." },
    { typ: "abc", zadani: "Urči číslo slovesa: SKÁČOU",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Skáče jeden, nebo víc? ONI skáčou.",
      vysvetleni: "SKÁČOU se říká o více lidech nebo zvířatech (ONI), proto je to číslo množné." },
    { typ: "abc", zadani: "Urči číslo slovesa: MALUJE",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 0,
      napoveda: "Maluje jeden, nebo víc? ON maluje.",
      vysvetleni: "MALUJE se říká o jednom člověku (ON, ONA), proto je to číslo jednotné." },
    { typ: "chyt", zadani: "Chyť sloveso v čísle množném:",
      moznosti: ["zpíváme", "zpívám", "zpíváš", "zpívá"], spravna: 0,
      napoveda: "Hledej tvar, ke kterému se hodí MY.",
      vysvetleni: "MY ZPÍVÁME – zpívá nás víc, proto číslo množné. Ostatní tvary říká jeden člověk." },
    { typ: "abc", zadani: "Kolik lidí mluví, když řekneme VAŘÍME?",
      moznosti: ["jeden člověk", "více lidí"], spravna: 1,
      napoveda: "Já vařím – jeden. My vaříme – ?",
      vysvetleni: "VAŘÍME říká více lidí (MY), proto je sloveso v čísle množném." },
    { typ: "chyt", zadani: "Chyť sloveso v čísle jednotném:",
      moznosti: ["běžím", "běžíme", "běžíte", "běhají"], spravna: 0,
      napoveda: "Hledej tvar, ke kterému se hodí JÁ.",
      vysvetleni: "JÁ BĚŽÍM – běží jen jeden, proto číslo jednotné. Ostatní tvary označují více lidí." },
    { typ: "abc", zadani: "Urči číslo slovesa: PLAVETE",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 1,
      napoveda: "Plave jeden, nebo víc? VY plavete.",
      vysvetleni: "PLAVETE říkáme více lidem (VY), proto je to číslo množné." }
  ],

  "sl_cas": [
    { typ: "abc", zadani: "Urči čas: BUDU ČÍST",
      moznosti: ["čas minulý", "čas přítomný", "čas budoucí"], spravna: 2,
      napoveda: "Už se to stalo, děje se to teď, nebo se to teprve stane?",
      vysvetleni: "BUDU ČÍST se teprve stane, proto je to čas budoucí. Pomáhá slovíčko BUDU." },
    { typ: "abc", zadani: "Urči čas: ČETL JSEM",
      moznosti: ["čas minulý", "čas přítomný", "čas budoucí"], spravna: 0,
      napoveda: "Už se to stalo?",
      vysvetleni: "ČETL JSEM se už stalo, proto je to čas minulý." },
    { typ: "abc", zadani: "Urči čas: ČTU",
      moznosti: ["čas minulý", "čas přítomný", "čas budoucí"], spravna: 1,
      napoveda: "Děje se to právě teď?",
      vysvetleni: "ČTU se děje právě teď, proto je to čas přítomný." },
    { typ: "abc", zadani: "„Včera jsme PLAVALI v bazénu.“ Sloveso PLAVALI JSME je v čase:",
      moznosti: ["minulém", "přítomném", "budoucím"], spravna: 0,
      napoveda: "Napoví ti slovo VČERA.",
      vysvetleni: "Stalo se to VČERA, tedy v minulosti. PLAVALI JSME je čas minulý." },
    { typ: "abc", zadani: "„Zítra POJEDEME na výlet.“ Sloveso POJEDEME je v čase:",
      moznosti: ["minulém", "přítomném", "budoucím"], spravna: 2,
      napoveda: "Napoví ti slovo ZÍTRA.",
      vysvetleni: "Stane se to ZÍTRA, tedy v budoucnosti. POJEDEME je čas budoucí." },
    { typ: "abc", zadani: "„Právě teď PÍŠU domácí úkol.“ Sloveso PÍŠU je v čase:",
      moznosti: ["minulém", "přítomném", "budoucím"], spravna: 1,
      napoveda: "Napoví ti slova PRÁVĚ TEĎ.",
      vysvetleni: "Děje se to PRÁVĚ TEĎ. PÍŠU je čas přítomný." },
    { typ: "chyt", zadani: "Chyť sloveso v čase budoucím:",
      moznosti: ["budeme zpívat", "zpíváme", "zpívali jsme", "zpívám"], spravna: 0,
      napoveda: "Hledej tvar se slovíčkem BUDEME.",
      vysvetleni: "BUDEME ZPÍVAT se teprve stane, proto čas budoucí. Zpíváme a zpívám jsou přítomný, zpívali jsme je minulý." },
    { typ: "chyt", zadani: "Chyť sloveso v čase minulém:",
      moznosti: ["skákal", "skáče", "bude skákat", "skáčeme"], spravna: 0,
      napoveda: "Hledej, co se už stalo.",
      vysvetleni: "SKÁKAL se už stalo, proto čas minulý. Skáče a skáčeme jsou přítomný, bude skákat je budoucí." }
  ],

  "sl_mix": [
    { typ: "abc", zadani: "Urči osobu: ZPÍVÁM",
      moznosti: ["1. osoba", "2. osoba", "3. osoba"], spravna: 0,
      napoveda: "Kdo zpívá? JÁ zpívám.",
      vysvetleni: "ZPÍVÁM říkám JÁ o sobě, proto 1. osoba." },
    { typ: "abc", zadani: "Urči číslo: ZPÍVÁM",
      moznosti: ["číslo jednotné", "číslo množné"], spravna: 0,
      napoveda: "Zpívá jeden člověk, nebo víc?",
      vysvetleni: "ZPÍVÁM říká jeden člověk (JÁ), proto číslo jednotné." },
    { typ: "abc", zadani: "Urči čas: BUDEME PSÁT",
      moznosti: ["čas minulý", "čas přítomný", "čas budoucí"], spravna: 2,
      napoveda: "Napoví ti slovíčko BUDEME.",
      vysvetleni: "BUDEME PSÁT se teprve stane, proto čas budoucí." },
    { typ: "abc", zadani: "Urči čas: VAŘILA",
      moznosti: ["čas minulý", "čas přítomný", "čas budoucí"], spravna: 0,
      napoveda: "Už se to stalo? Maminka včera VAŘILA.",
      vysvetleni: "VAŘILA se už stalo, proto čas minulý." },
    { typ: "abc", zadani: "Urči osobu a číslo: MLUVÍTE",
      moznosti: ["2. osoba, číslo množné", "1. osoba, číslo jednotné", "3. osoba, číslo množné"], spravna: 0,
      napoveda: "Kdo mluví? VY mluvíte.",
      vysvetleni: "MLUVÍTE říkáme VÁM – VY je 2. osoba a je vás víc, proto číslo množné." },
    { typ: "abc", zadani: "Urči čas: HRAJEME SI",
      moznosti: ["čas minulý", "čas přítomný", "čas budoucí"], spravna: 1,
      napoveda: "Děje se to právě teď?",
      vysvetleni: "HRAJEME SI se děje právě teď, proto čas přítomný." },
    { typ: "chyt", zadani: "Chyť sloveso:",
      moznosti: ["skáče", "míč", "vysoko", "hřiště"], spravna: 0,
      napoveda: "Sloveso říká, co kdo dělá.",
      vysvetleni: "SKÁČE je sloveso – říká, co kdo dělá. Míč a hřiště jsou podstatná jména, vysoko je příslovce." },
    { typ: "abc", zadani: "Urči osobu, číslo a čas: ČETLI JSME",
      moznosti: ["1. osoba, číslo množné, čas minulý", "3. osoba, číslo jednotné, čas přítomný", "1. osoba, číslo množné, čas budoucí"], spravna: 0,
      napoveda: "Kdo četl? MY jsme četli. A už se to stalo.",
      vysvetleni: "ČETLI JSME říkáme MY o sobě (1. osoba), je nás víc (číslo množné) a už se to stalo (čas minulý)." }
  ]
};

// ----------------------------------------------------------
// SEZNAM ÚROVNÍ – pořadí a názvy
// ----------------------------------------------------------
const UROVNE = [
  { id: "vs_b",    planeta: "ypsilonka", nazev: "Po B", ikona: "B" },
  { id: "vs_l",    planeta: "ypsilonka", nazev: "Po L", ikona: "L" },
  { id: "vs_m",    planeta: "ypsilonka", nazev: "Po M", ikona: "M" },
  { id: "vs_p",    planeta: "ypsilonka", nazev: "Po P", ikona: "P" },
  { id: "vs_s",    planeta: "ypsilonka", nazev: "Po S", ikona: "S" },
  { id: "vs_v",    planeta: "ypsilonka", nazev: "Po V", ikona: "V" },
  { id: "vs_z",    planeta: "ypsilonka", nazev: "Po Z", ikona: "Z" },
  { id: "vs_mix",  planeta: "ypsilonka", nazev: "Závěrečná mise", ikona: "★" },
  { id: "pj_rod",   planeta: "podstatka", nazev: "Rod", ikona: "R" },
  { id: "pj_cislo", planeta: "podstatka", nazev: "Číslo", ikona: "Č" },
  { id: "pj_pad",   planeta: "podstatka", nazev: "Pád", ikona: "P" },
  { id: "pj_mix",   planeta: "podstatka", nazev: "Kombinovaná mise", ikona: "★" },
  { id: "sl_osoba", planeta: "slovesna", nazev: "Osoba", ikona: "O" },
  { id: "sl_cislo", planeta: "slovesna", nazev: "Číslo", ikona: "Č" },
  { id: "sl_cas",   planeta: "slovesna", nazev: "Čas", ikona: "Č" },
  { id: "sl_mix",   planeta: "slovesna", nazev: "Kombinovaná mise", ikona: "★" }
];

const PLANETY = [
  { id: "ypsilonka", nazev: "Planeta Ypsilonka", tema: "Vyjmenovaná slova",
    emoji: "🪐", trida: "planeta-ypsilonka",
    odznak: "Mistr vyjmenovaných slov", razitko: "🟡" },
  { id: "podstatka", nazev: "Planeta Podstatka", tema: "Podstatná jména",
    emoji: "🟠", trida: "planeta-podstatka",
    odznak: "Znalec podstatných jmen", razitko: "🟠" },
  { id: "slovesna", nazev: "Stanice Slovesná", tema: "Slovesa",
    emoji: "🛰️", trida: "planeta-slovesna",
    odznak: "Kapitán sloves", razitko: "🟣" }
];
